import type { Metadata } from "next";
import { manrope, roboto } from "./ui/fonts/fonts";
import "./globals.css";
import { NavbarWithMegaMenu } from "@/components/ui/megamenu";

import Footer from "@/components/ui/footer";
import Toaster from "@/components/ui/toaster";
// import { usePathname } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} ${manrope.className} antialiased`}>
        {/* <StickyNavbar /> */}
        <Toaster />
        <NavbarWithMegaMenu />

        {children}
        <Footer />
      </body>
    </html>
  );
}

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const pathname = usePathname();
//   const isDashboard = pathname.startsWith("/dashboard");

//   return (
//     <html lang="en">
//       <body className={`${roboto.className} ${manrope.className} antialiased`}>
//         {!isDashboard && <NavbarWithMegaMenu />}
//         {children}
//         {!isDashboard && <Footer />}
//       </body>
//     </html>
//   );
// }
