import type { Metadata } from "next";
import { manrope, roboto } from "./ui/fonts/fonts";
import "./globals.css";
import { NavbarWithMegaMenu } from "@/components/ui/megamenu";
import Footer from "@/components/ui/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${manrope.className} antialiased`}>
        {/* <StickyNavbar /> */}
        <NavbarWithMegaMenu />

        {children}
        <Footer />
      </body>
    </html>
  );
}
